### ISSUE TITLE
error TS2724: no exported member named 'ConstArgumentNode'

### ISSUE THREAD

**Issue by danbrakeley** [0no-co/graphql.web#44]
### Describe the bug

1. Create a new node/typescript project.
2. npm install @amplitude/ampli v1.35.0.
   - note that ampli depends on graphql ^v15.4.0. Actual version in my lock file was v15.9.0.
3. npm install @urql/core v5.0.8, which depends on @0no-co/graphql.web (my lock file showed v1.0.11).
4. create an index.ts that imports anything from @urql/core

Result: Typescript compilation errors in the form:

```text
./../node_modules/@0no-co/graphql.web/dist/graphql.web.d.ts:456:11 - error TS2724: '"/home/user/app/node_modules/graphql/index"' has no exported member named 'ConstArgumentNode'. Did you mean 'ArgumentNode'?

456   GraphQL.ConstArgumentNode,
              ~~~~~~~~~~~~~~~~~
```

I actually get 6 errors, for ConstArgumentNode, ConstValueNode, ConstListValueNode, ConstObjectValueNode, ConstObjectFieldNode, and ConstDirectiveNode.

I suspect this is due to the 0no-co/graphql.web peerDependency for versions `14 - 16`. It seems v15.9.0, at least, is missing some types that 0no-co/graphql.web depends on.

Workaround: explicitly install latest graphql (v16.9.0).

### Reproduction

https://github.com/danbrakeley/0no-co-graphql.web-peer-dep-bug

### Package version

- `@urql/core`: v5.0.8
- `@0no-co/graphql.web`: v1.0.11

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which GitHub Discussions should be used
- [X] Follow our [Code of Conduct](https://github.com/0no-co/graphql.web/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This is expected, a `ConstArgumentNode` is not part of the execution language, it's part of the SchemaDefinition language. This is an implementation for the web which makes it so that we focus on the execution language. Why do you need parts of the Schema Definition language? If you need them you can alias to `graphql` or `graphql-web-lite`

**Comment by kitten** [comment]
seconding the above. We need to keep peer dependencies somewhat open for many dependency chains where GraphQL 15 still occurs.

However, in application code and code bases directly depending on our dependency, there shouldn't be any reason to still depend on GraphQL 15.

I don't know what Amplitude is but please report this to them. It doesn't seem like they've upgraded their CLI's dependencies then in 3+(?) years?
Another solution is to install this CLI globally or separately instead,
or to make sure that your root dependency of graphql is set to `^16`, to prevent your package manager of finding the smaller range. This should definitely resolve this ✌️
