### ISSUE TITLE
Inconsistent print from graphql

### ISSUE THREAD

**Issue by jasonkuhrt** [0no-co/graphql.web#45]
### Describe the bug

Given this document:

```
{
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: undefined,
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'id' },
            alias: undefined,
            arguments: [],
            directives: [],
            selectionSet: { kind: 'SelectionSet', selections: [] }
          }
        ]
      },
      variableDefinitions: []
    }
  ]
}
```

The result is:

```graphql
{
  id {
    
  }
}
```

But when using `print` from the `graphql@16.9.x` package it is:

```graphql
{
  id
}
```

### Reproduction

See above

### Package version

`1.0.11`

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which GitHub Discussions should be used
- [X] Follow our [Code of Conduct](https://github.com/0no-co/graphql.web/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This is fixed and released in 1.0.12! Thanks for the report
